name: [CoE Starter Kit] Bug report
description: 	Create a report to help us improve the CoE Starter Kit
title: "[CoE Starter Kit - BUG]: your issue description"
labels: [coe-starter-kit]
assignees:
  - JeneferM-MSFT
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug?
      description: A clear and concise description of what the bug is.
       Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Tell us what happened!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Please tell us which solution, flow or app you are experiencing issues with.
      options:
        - Core Components
        - Governance Components
        - Audit Log Components
        - Nurture Components
        - Innovation Backlog
        - Theming
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of the solution are you using?
      placeholder: 1.70
    validations:
      required: false
  - type: textarea
    id: what-flowapp
    attributes:
      label: App or Flow?
      description: What app or flow are you seeing the issue with?
      placeholder: App Catalog
      value: "A bug happened!"
    validations:
      required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
