# This pipeline gets triggered manually or via an API call.  
# It is a general purpose automation that allows you to export a solution from a CDS environment and commit it to a git branch.
# It facilitates:
# -Ensuring user can be part of the commit (instead of a generic user), thereby enabling tracking of who made what changes
# -Reuse for any solution in any CDS environment

# The following variables need to be set when the pipeline is queued to run:
# Project: The name of the Azure DevOps Project to which we are exporting our solution.
# Repo: The name of the Azure DevOps Repo to which we are exporting our solution.
# Branch: The name of the Azure DevOps Branch in the Repo above to which we are exporting our solution.
# BranchToCreate: The name of the new Azure DevOps Branch to create in the Repo above to which we are exporting our solution (Optional).
# CommitMessage: The commit message for this commit.
# Email: The email of the user performing the commit.
# ServiceConnName: The name of the service connection to Power Platform from which we'll be pulling the solution.
# SolutionName: The name of the solution being exported (i.e. Not the Display Name).
# TriggerSolutionUpgrade: A flag to determine if a subsequent Pull Request will perform an upgrade in the target environment.
# UserName: The Display name of the user performing the commit.

trigger: none

name: export-$(SolutionName)-to-git-branch

variables:
- group: global-variable-group

pool:
  vmImage: 'windows-2019'

steps:
# Checkout Pipelines
- checkout: self
  path: 'PipelineUtils'
  displayName: 'Checkout Pipeline Branch'

# Checkout our Branch
- checkout: git://$(Project)/$(Repo)@$(Branch)
  displayName: 'Checkout Source Branch'

# Configure email/name and checkout git branch
- script: |
   git config user.email "$(Email)"
   git config user.name "$(UserName)"
   git checkout origin/$(Branch) --track
  workingDirectory: $(Build.SourcesDirectory)\$(Repo)
  displayName: 'Initialize Git'

# If the BranchToCreate variable *does not* contain an empty string, then
# create a branch based on BranchToCreate variable value and checkout that branch.
- script: |
   git checkout -b $(BranchToCreate) $(Branch)
  displayName: 'Create New Git Branch: $(BranchToCreate)'
  workingDirectory: $(Build.SourcesDirectory)\$(Repo)
  condition: and(succeeded(), ne(variables['BranchToCreate'], '')) # If an empty value is passed for the BranchToCreate variable, then skip this task

- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.tool-installer.PowerPlatformToolInstaller@0
  displayName: 'Install Power Platform Build Tools'

# Before exporting the solution, publish solution customizations to ensure all the changes are exported
- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.publish-customizations.PowerPlatformPublishCustomizations@0
  displayName: 'Publish Customizations'
  inputs:
    authenticationType: PowerPlatformSPN
    PowerPlatformSPN: '$(ServiceConnName)'

# Export both unmanaged and managed to put into source control
- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.export-solution.PowerPlatformExportSolution@0
  displayName: 'Export Unmanaged Solution'
  inputs:
    authenticationType: PowerPlatformSPN
    PowerPlatformSPN: '$(ServiceConnName)'
    SolutionName: '$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip'

- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.export-solution.PowerPlatformExportSolution@0
  displayName: 'Export Managed Solution'
  inputs:
    authenticationType: PowerPlatformSPN
    PowerPlatformSPN: '$(ServiceConnName)'
    SolutionName: '$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName)_managed.zip'
    Managed: true

# Unpack contents of solution to make the contents source control friendly 
- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.unpack-solution.PowerPlatformUnpackSolution@0
  displayName: 'Power Platform Unpack Solution'
  inputs:
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip'
    SolutionTargetFolder: '$(Build.SourcesDirectory)\$(Repo)\$(SolutionName)\SolutionPackage'
    SolutionType: Both

# Solution version in source control is not used.  We create the solution version at build time from the current build number.  
# Therefore, we will zero out the solution version in source control.
- task: knom.regexreplace-task.regex-replace.RegexReplace@3
  displayName: 'Update Solution XML with Build Number'
  inputs:
    InputSearchPattern: |
      $(Build.SourcesDirectory)\$(Repo)\$(SolutionName)\SolutionPackage\**\Solution.xml
    FindRegex: '<Version>[\s\S]*?<\/Version>'
    ReplaceRegex: '<Version>0.0.0.0</Version>'

# Use temp exe from PowerShell to unpack source files into a folder
- pwsh: |
   Get-ChildItem -Path $(Build.SourcesDirectory)\$(Repo)\$(SolutionName) -Recurse -Filter *.msapp | 
   ForEach-Object {
      $unpackedPath = $_.FullName.Replace(".msapp", "_msapp_src")
      $(Pipeline.Workspace)\PipelineUtils\Pipelines\temp-canvas-packager\temp-canvas-packager.exe -unpack $_.FullName $unpackedPath
      del $_.FullName
   }
  displayName: 'unpack msapp files'
  enabled: true

# TEMPORARY until SolutionPackager supports formatting json files on unpack we
# update all the json files to be pretty-print / formatted so they are easier to read in source control.
# This also makes it easier to read changes from one commit to another
- powershell: |
   Invoke-WebRequest -Uri https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile  jq.exe
   Get-ChildItem -Path $(Build.SourcesDirectory)\$(Repo)\$(SolutionName) -Recurse -Filter *.json | 
   ForEach-Object {
       $formatted = .\jq.exe . $_.FullName
       $formatted | Out-File $_.FullName 
   }
   del jq.exe
   del $(Build.ArtifactStagingDirectory)\$(SolutionName).zip
   del $(Build.ArtifactStagingDirectory)\$(SolutionName)_managed.zip
  displayName: 'Format JSON files'
  enabled: true

- powershell: |
    git add --all
  workingDirectory: $(Build.SourcesDirectory)\$(Repo)
  displayName: 'Add Changes to Git Branch'

# Commit all changes to Git branch. If there are no changes we want to warn the user that there was nothing to commit. As this could mean there was a user error involved.
- powershell: |
    $gitStatus = iex "git status --porcelain"
    if ($gitStatus) 
    {
        git commit -m "$(CommitMessage)"
    }
    else 
    {
        Write-Host "##vso[task.logissue type=warning]There is nothing to commit. No changes have been made since the previous commit. If this is unexpected make sure your changes have been published before committing again."
        exit 1;
    }
  workingDirectory: $(Build.SourcesDirectory)\$(Repo)
  displayName: 'Commit Changes to Git Branch'
  continueOnError: true

# If BranchToCreate variable value is '', then push to the branch specified in the Branch variable
- script: |
   git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin $(Branch)
  workingDirectory: $(Build.SourcesDirectory)\$(Repo)
  displayName: 'Push to $(Branch) Branch'
  condition: and(succeeded(), eq(variables['BranchToCreate'], '')) # If an empty value is passed for the BranchToCreate variable, then run this task

# If BranchToCreate variable value is not '', then push to the branch specified in the BranchToCreate variable
- script: |
   git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin $(BranchToCreate)
  workingDirectory: $(Build.SourcesDirectory)\$(Repo)
  displayName: 'Push to $(BranchToCreate) Branch'
  condition: and(succeeded(), ne(variables['BranchToCreate'], '')) # If an empty value is not passed for the BranchToCreate variable, then run this task

# Task below saves the value of the TriggerSolutionUpgrade variable to a json file which will be read by the build that kicks off after code is committed to the branch.
- task: nkdagility.variablehydration.variabledehydration-task.variabledehydration@0
  displayName: 'Save Build Variable TriggerSolutionUpgrade'
  inputs:
    prefixes: TRIGGERSOLUTIONUPGRADE

# Since we are saving the value of the TriggerSolutionUpgrade variable to a json file, we need to publish it as an artifact to be picked up by the build that kicks off after 
# code is committed to the branch 
- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: drop

# Since this is a general purpose pipeline that can be used to commit any solution package to a git branch, we need to tag it so the builds trigger by changes made to each 
# solution picks up the right artifact containing the TriggerSolutionUpgrade variable value 
- task: tagBuildOrRelease@0
  inputs:
    type: 'Build'
    tags: '$(SolutionName)'