[book]
title = "COE Toolkit Command Line Interface"
authors = [ "Grant Archibald", "Microsoft PowerCAT"]
description = "Description of the Power Platform Center of Excellence Command Line Interface"
src = "."  # the source files will be found in `root/my-src` instead of `root/src`
language = "en"

[output.epub]
additional-css = ["../book.css"]
use-default-css = false